export const countriesPortuguese = {
    4: { "name": "Afeganistão", "alpha2": "af", "alpha3": "afg" },
    710: { "name": "África do Sul", "alpha2": "za", "alpha3": "zaf" },
    8: { "name": "Albânia", "alpha2": "al", "alpha3": "alb" },
    276: { "name": "Alemanha", "alpha2": "de", "alpha3": "deu" },
    20: { "name": "Andorra", "alpha2": "ad", "alpha3": "and" },
    24: { "name": "Angola", "alpha2": "ao", "alpha3": "ago" },
    28: { "name": "Antígua e Barbuda", "alpha2": "ag", "alpha3": "atg" },
    682: { "name": "Arábia Saudita", "alpha2": "sa", "alpha3": "sau" },
    12: { "name": "Argélia", "alpha2": "dz", "alpha3": "dza" },
    32: { "name": "Argentina", "alpha2": "ar", "alpha3": "arg" },
    51: { "name": "Armênia", "alpha2": "am", "alpha3": "arm" },
    36: { "name": "Austrália", "alpha2": "au", "alpha3": "aus" },
    40: { "name": "Áustria", "alpha2": "at", "alpha3": "aut" },
    31: { "name": "Azerbaijão", "alpha2": "az", "alpha3": "aze" },
    44: { "name": "Bahamas", "alpha2": "bs", "alpha3": "bhs" },
    48: { "name": "Bahrein", "alpha2": "bh", "alpha3": "bhr" },
    50: { "name": "Bangladesh", "alpha2": "bd", "alpha3": "bgd" },
    52: { "name": "Barbados", "alpha2": "bb", "alpha3": "brb" },
    56: { "name": "Bélgica", "alpha2": "be", "alpha3": "bel" },
    84: { "name": "Belize", "alpha2": "bz", "alpha3": "blz" },
    204: { "name": "Benim", "alpha2": "bj", "alpha3": "ben" },
    112: { "name": "Bielorrússia", "alpha2": "by", "alpha3": "blr" },
    68: { "name": "Bolívia", "alpha2": "bo", "alpha3": "bol" },
    70: { "name": "Bósnia e Herzegovina", "alpha2": "ba", "alpha3": "bih" },
    72: { "name": "Botswana", "alpha2": "bw", "alpha3": "bwa" },
    76: { "name": "Brasil", "alpha2": "br", "alpha3": "bra" },
    96: { "name": "Brunei", "alpha2": "bn", "alpha3": "brn" },
    100: { "name": "Bulgária", "alpha2": "bg", "alpha3": "bgr" },
    854: { "name": "Burkina Faso", "alpha2": "bf", "alpha3": "bfa" },
    108: { "name": "Burundi", "alpha2": "bi", "alpha3": "bdi" },
    64: { "name": "Butão", "alpha2": "bt", "alpha3": "btn" },
    132: { "name": "Cabo Verde", "alpha2": "cv", "alpha3": "cpv" },
    116: { "name": "Camboja", "alpha2": "kh", "alpha3": "khm" },
    120: { "name": "Camarões", "alpha2": "cm", "alpha3": "cmr" },
    124: { "name": "Canadá", "alpha2": "ca", "alpha3": "can" },
    398: { "name": "Cazaquistão", "alpha2": "kz", "alpha3": "kaz" },
    140: { "name": "República Centro-Africana", "alpha2": "cf", "alpha3": "caf" },
    148: { "name": "Chade", "alpha2": "td", "alpha3": "tcd" },
    203: { "name": "República Tcheca", "alpha2": "cz", "alpha3": "cze" },
    152: { "name": "Chile", "alpha2": "cl", "alpha3": "chl" },
    156: { "name": "China", "alpha2": "cn", "alpha3": "chn" },
    196: { "name": "Chipre", "alpha2": "cy", "alpha3": "cyp" },
    170: { "name": "Colômbia", "alpha2": "co", "alpha3": "col" },
    174: { "name": "Comores", "alpha2": "km", "alpha3": "com" },
    178: { "name": "República do Congo", "alpha2": "cg", "alpha3": "cog" },
    180: { "name": "República Democrática do Congo", "alpha2": "cd", "alpha3": "cod" },
    410: { "name": "Coreia do Sul", "alpha2": "kr", "alpha3": "kor" },
    408: { "name": "Coreia do Norte", "alpha2": "kp", "alpha3": "prk" },
    384: { "name": "Costa do Marfim", "alpha2": "ci", "alpha3": "civ" },
    188: { "name": "Costa Rica", "alpha2": "cr", "alpha3": "cri" },
    191: { "name": "Croácia", "alpha2": "hr", "alpha3": "hrv" },
    192: { "name": "Cuba", "alpha2": "cu", "alpha3": "cub" },
    208: { "name": "Dinamarca", "alpha2": "dk", "alpha3": "dnk" },
    262: { "name": "Djibouti", "alpha2": "dj", "alpha3": "dji" },
    212: { "name": "Dominica", "alpha2": "dm", "alpha3": "dma" },
    214: { "name": "República Dominicana", "alpha2": "do", "alpha3": "dom" },
    818: { "name": "Egito", "alpha2": "eg", "alpha3": "egy" },
    222: { "name": "El Salvador", "alpha2": "sv", "alpha3": "slv" },
    784: { "name": "Emirados Árabes Unidos", "alpha2": "ae", "alpha3": "are" },
    218: { "name": "Equador", "alpha2": "ec", "alpha3": "ecu" },
    232: { "name": "Eritreia", "alpha2": "er", "alpha3": "eri" },
    703: { "name": "Eslováquia", "alpha2": "sk", "alpha3": "svk" },
    705: { "name": "Eslovênia", "alpha2": "si", "alpha3": "svn" },
    724: { "name": "Espanha", "alpha2": "es", "alpha3": "esp" },
    840: { "name": "Estados Unidos", "alpha2": "us", "alpha3": "usa" },
    233: { "name": "Estónia", "alpha2": "ee", "alpha3": "est" },
    231: { "name": "Etiópia", "alpha2": "et", "alpha3": "eth" },
    242: { "name": "Fiji", "alpha2": "fj", "alpha3": "fji" },
    608: { "name": "Filipinas", "alpha2": "ph", "alpha3": "phl" },
    246: { "name": "Finlândia", "alpha2": "fi", "alpha3": "fin" },
    250: { "name": "França", "alpha2": "fr", "alpha3": "fra" },
    266: { "name": "Gabão", "alpha2": "ga", "alpha3": "gab" },
    270: { "name": "Gâmbia", "alpha2": "gm", "alpha3": "gmb" },
    288: { "name": "Gana", "alpha2": "gh", "alpha3": "gha" },
    268: { "name": "Geórgia", "alpha2": "ge", "alpha3": "geo" },
    300: { "name": "Grécia", "alpha2": "gr", "alpha3": "grc" },
    308: { "name": "Granada", "alpha2": "gd", "alpha3": "grd" },
    320: { "name": "Guatemala", "alpha2": "gt", "alpha3": "gtm" },
    328: { "name": "Guiana", "alpha2": "gy", "alpha3": "guy" },
    624: { "name": "Guiné-Bissau", "alpha2": "gw", "alpha3": "gnb" },
    324: { "name": "Guiné", "alpha2": "gn", "alpha3": "gin" },
    226: { "name": "Guiné Equatorial", "alpha2": "gq", "alpha3": "gnq" },
    332: { "name": "Haiti", "alpha2": "ht", "alpha3": "hti" },
    340: { "name": "Honduras", "alpha2": "hn", "alpha3": "hnd" },
    348: { "name": "Hungria", "alpha2": "hu", "alpha3": "hun" },
    887: { "name": "Iêmen", "alpha2": "ye", "alpha3": "yem" },
    356: { "name": "Índia", "alpha2": "in", "alpha3": "ind" },
    360: { "name": "Indonésia", "alpha2": "id", "alpha3": "idn" },
    368: { "name": "Iraque", "alpha2": "iq", "alpha3": "irq" },
    364: { "name": "Irã", "alpha2": "ir", "alpha3": "irn" },
    372: { "name": "Irlanda", "alpha2": "ie", "alpha3": "irl" },
    352: { "name": "Islândia", "alpha2": "is", "alpha3": "isl" },
    376: { "name": "Israel", "alpha2": "il", "alpha3": "isr" },
    380: { "name": "Itália", "alpha2": "it", "alpha3": "ita" },
    388: { "name": "Jamaica", "alpha2": "jm", "alpha3": "jam" },
    392: { "name": "Japão", "alpha2": "jp", "alpha3": "jpn" },
    400: { "name": "Jordânia", "alpha2": "jo", "alpha3": "jor" },
    296: { "name": "Kiribati", "alpha2": "ki", "alpha3": "kir" },
    414: { "name": "Kuwait", "alpha2": "kw", "alpha3": "kwt" },
    418: { "name": "Laos", "alpha2": "la", "alpha3": "lao" },
    426: { "name": "Lesoto", "alpha2": "ls", "alpha3": "lso" },
    428: { "name": "Letônia", "alpha2": "lv", "alpha3": "lva" },
    422: { "name": "Líbano", "alpha2": "lb", "alpha3": "lbn" },
    430: { "name": "Libéria", "alpha2": "lr", "alpha3": "lbr" },
    434: { "name": "Líbia", "alpha2": "ly", "alpha3": "lby" },
    438: { "name": "Liechtenstein", "alpha2": "li", "alpha3": "lie" },
    440: { "name": "Lituânia", "alpha2": "lt", "alpha3": "ltu" },
    442: { "name": "Luxemburgo", "alpha2": "lu", "alpha3": "lux" },
    807: { "name": "Macedônia do Norte", "alpha2": "mk", "alpha3": "mkd" },
    450: { "name": "Madagáscar", "alpha2": "mg", "alpha3": "mdg" },
    458: { "name": "Malásia", "alpha2": "my", "alpha3": "mys" },
    454: { "name": "Malawi", "alpha2": "mw", "alpha3": "mwi" },
    462: { "name": "Maldivas", "alpha2": "mv", "alpha3": "mdv" },
    466: { "name": "Mali", "alpha2": "ml", "alpha3": "mli" },
    470: { "name": "Malta", "alpha2": "mt", "alpha3": "mlt" },
    504: { "name": "Marrocos", "alpha2": "ma", "alpha3": "mar" },
    584: { "name": "Ilhas Marshall", "alpha2": "mh", "alpha3": "mhl" },
    480: { "name": "Maurícia", "alpha2": "mu", "alpha3": "mus" },
    478: { "name": "Mauritânia", "alpha2": "mr", "alpha3": "mrt" },
    484: { "name": "México", "alpha2": "mx", "alpha3": "mex" },
    104: { "name": "Mianmar", "alpha2": "mm", "alpha3": "mmr" },
    583: { "name": "Estados Federados da Micronésia", "alpha2": "fm", "alpha3": "fsm" },
    508: { "name": "Moçambique", "alpha2": "mz", "alpha3": "moz" },
    498: { "name": "Moldávia", "alpha2": "md", "alpha3": "mda" },
    492: { "name": "Mónaco", "alpha2": "mc", "alpha3": "mco" },
    496: { "name": "Mongólia", "alpha2": "mn", "alpha3": "mng" },
    499: { "name": "Montenegro", "alpha2": "me", "alpha3": "mne" },
    516: { "name": "Namíbia", "alpha2": "na", "alpha3": "nam" },
    520: { "name": "Nauru", "alpha2": "nr", "alpha3": "nru" },
    524: { "name": "Nepal", "alpha2": "np", "alpha3": "npl" },
    558: { "name": "Nicarágua", "alpha2": "ni", "alpha3": "nic" },
    562: { "name": "Níger", "alpha2": "ne", "alpha3": "ner" },
    566: { "name": "Nigéria", "alpha2": "ng", "alpha3": "nga" },
    578: { "name": "Noruega", "alpha2": "no", "alpha3": "nor" },
    554: { "name": "Nova Zelândia", "alpha2": "nz", "alpha3": "nzl" },
    512: { "name": "Omã", "alpha2": "om", "alpha3": "omn" },
    528: { "name": "Países Baixos", "alpha2": "nl", "alpha3": "nld" },
    585: { "name": "Palau", "alpha2": "pw", "alpha3": "plw" },
    591: { "name": "Panamá", "alpha2": "pa", "alpha3": "pan" },
    598: { "name": "Papua-Nova Guiné", "alpha2": "pg", "alpha3": "png" },
    586: { "name": "Paquistão", "alpha2": "pk", "alpha3": "pak" },
    600: { "name": "Paraguai", "alpha2": "py", "alpha3": "pry" },
    604: { "name": "Peru", "alpha2": "pe", "alpha3": "per" },
    616: { "name": "Polônia", "alpha2": "pl", "alpha3": "pol" },
    620: { "name": "Portugal", "alpha2": "pt", "alpha3": "prt" },
    634: { "name": "Catar", "alpha2": "qa", "alpha3": "qat" },
    404: { "name": "Quênia", "alpha2": "ke", "alpha3": "ken" },
    417: { "name": "Quirguistão", "alpha2": "kg", "alpha3": "kgz" },
    826: { "name": "Reino Unido", "alpha2": "gb", "alpha3": "gbr" },
    642: { "name": "Romênia", "alpha2": "ro", "alpha3": "rou" },
    646: { "name": "Ruanda", "alpha2": "rw", "alpha3": "rwa" },
    643: { "name": "Rússia", "alpha2": "ru", "alpha3": "rus" },
    882: { "name": "Samoa", "alpha2": "ws", "alpha3": "wsm" },
    90: { "name": "Ilhas Salomão", "alpha2": "sb", "alpha3": "slb" },
    674: { "name": "San Marino", "alpha2": "sm", "alpha3": "smr" },
    662: { "name": "Santa Lúcia", "alpha2": "lc", "alpha3": "lca" },
    659: { "name": "São Cristóvão e Névis", "alpha2": "kn", "alpha3": "kna" },
    678: { "name": "São Tomé e Príncipe", "alpha2": "st", "alpha3": "stp" },
    670: { "name": "São Vicente e Granadinas", "alpha2": "vc", "alpha3": "vct" },
    686: { "name": "Senegal", "alpha2": "sn", "alpha3": "sen" },
    694: { "name": "Serra Leoa", "alpha2": "sl", "alpha3": "sle" },
    688: { "name": "Sérvia", "alpha2": "rs", "alpha3": "srb" },
    690: { "name": "Seicheles", "alpha2": "sc", "alpha3": "syc" },
    702: { "name": "Singapura", "alpha2": "sg", "alpha3": "sgp" },
    760: { "name": "Síria", "alpha2": "sy", "alpha3": "syr" },
    706: { "name": "Somália", "alpha2": "so", "alpha3": "som" },
    144: { "name": "Sri Lanka", "alpha2": "lk", "alpha3": "lka" },
    748: { "name": "Essuatíni", "alpha2": "sz", "alpha3": "swz" },
    729: { "name": "Sudão", "alpha2": "sd", "alpha3": "sdn" },
    728: { "name": "Sudão do Sul", "alpha2": "ss", "alpha3": "ssd" },
    752: { "name": "Suécia", "alpha2": "se", "alpha3": "swe" },
    756: { "name": "Suíça", "alpha2": "ch", "alpha3": "che" },
    740: { "name": "Suriname", "alpha2": "sr", "alpha3": "sur" },
    764: { "name": "Tailândia", "alpha2": "th", "alpha3": "tha" },
    762: { "name": "Tajiquistão", "alpha2": "tj", "alpha3": "tjk" },
    834: { "name": "Tanzânia", "alpha2": "tz", "alpha3": "tza" },
    626: { "name": "Timor-Leste", "alpha2": "tl", "alpha3": "tls" },
    768: { "name": "Togo", "alpha2": "tg", "alpha3": "tgo" },
    776: { "name": "Tonga", "alpha2": "to", "alpha3": "ton" },
    780: { "name": "Trinidad e Tobago", "alpha2": "tt", "alpha3": "tto" },
    788: { "name": "Tunísia", "alpha2": "tn", "alpha3": "tun" },
    795: { "name": "Turquemenistão", "alpha2": "tm", "alpha3": "tkm" },
    792: { "name": "Turquia", "alpha2": "tr", "alpha3": "tur" },
    798: { "name": "Tuvalu", "alpha2": "tv", "alpha3": "tuv" },
    804: { "name": "Ucrânia", "alpha2": "ua", "alpha3": "ukr" },
    800: { "name": "Uganda", "alpha2": "ug", "alpha3": "uga" },
    858: { "name": "Uruguai", "alpha2": "uy", "alpha3": "ury" },
    860: { "name": "Uzbequistão", "alpha2": "uz", "alpha3": "uzb" },
    548: { "name": "Vanuatu", "alpha2": "vu", "alpha3": "vut" },
    862: { "name": "Venezuela", "alpha2": "ve", "alpha3": "ven" },
    704: { "name": "Vietnã", "alpha2": "vn", "alpha3": "vnm" },
    894: { "name": "Zâmbia", "alpha2": "zm", "alpha3": "zmb" },
    716: { "name": "Zimbabwe", "alpha2": "zw", "alpha3": "zwe" },
    1010: { "name": "Ilhas do Canal", "alpha2": "um", "alpha3": "umi" }
}